booking/urls.py
from django.urls import path
from .views import detailBookingView, reserve_seat, BookingListView, BookingDeleteView
app_name = 'booking'
urlpatterns = [
    path('select-seat/<int:show_id>/', reserve_seat, name='reserve_seat'),
    path('booking/', BookingListView.as_view(), name='list'),
    path('booking/<str:btid>/delete/',
         BookingDeleteView.as_view(), name='delete'),
    path('booking/<str:btid>/', detailBookingView, name='detail'),
]

movie/urls.py
from django.urls import path
from .views import *
app_name = 'movie'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('<int:movie_id>/', movie_details, name='detail'),
    path('search/', SearchView.as_view(), name='search'),
    path('movies/', MovieListView.as_view(), name='movie-list'),
    path('admin/add-movie', add_movie, name='add-movie'),
    path('admin/add-show', add_show, name='add-show'),

]

movie_booking/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('movie.urls')),
    path('', include('booking.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie/models.py
import datetime
from django.urls import reverse
from django.contrib.auth import get_user_model
import uuid
from django.db import models
from django.db.models import Q
from django.urls.base import reverse
from datetime import datetime, timedelta
# Create your models here.


class MovieQuerySet(models.query.QuerySet):
    def search(self, query):
        lookup = (
            Q(moviename__icontains=query)
        )
        return self.filter(lookup).distinct()


class MovieManager(models.Manager):
    def get_queryset(self):
        return MovieQuerySet(self.model, self._db)

    def search(self, query):
        return self.get_queryset().search(query)


User = get_user_model()
# Create your models here.


class Screen(models.Model):
    name = models.CharField(max_length=20)
    seats = models.IntegerField(default=10)

    def __str__(self) -> str:
        return str("Screen : "+self.name)


class Movie(models.Model):
    moviename = models.CharField("Movie Name", max_length=20, blank=False)
    poster = models.ImageField(
        null=True, blank=False, upload_to='%Y/%m/%d/')
    ticket_price = models.FloatField(null=False, blank=False)
    added = models.DateTimeField(auto_now_add=True)
    screen = models.ManyToManyField(Screen)
    objects = MovieManager()

    def get_absolute_url(self):
        return reverse('movie:detail', kwargs={'movie_id': self.pk})

    def __str__(self):
        return self.moviename

class Show(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    screen = models.ForeignKey(Screen, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()

    def __str__(self):
        return str(self.movie)+" : "+str(self.screen)+"-"+str(self.date)+"-"+str(self.time)


class Seat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    show = models.ForeignKey(Show, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    screen = models.ForeignKey(Screen, on_delete=models.CASCADE)
    seat_no = models.IntegerField()

    def __str__(self):
        return str(self.id)


class Booking(models.Model):
    id = models.CharField(max_length=255, primary_key=True)
    transaction_id = models.UUIDField(unique=True, editable=False,
                                      default=uuid.uuid4)
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)
    seat = models.ForeignKey(Seat, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    show = models.ForeignKey(Show, on_delete=models.CASCADE)
    paid_amount = models.DecimalField(max_digits=8, decimal_places=2)
    paid_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return str("Booking ID # "+str(self.transaction_id))

    def get_absolute_url(self):
        return reverse('booking:detail', kwargs={'btid': self.id})

    @property
    def cancel_time(self):
        d = datetime.now()+timedelta(days=1)
        dd = datetime.strptime(str(self.show.date)+" "+str(
            self.show.time), '%Y-%m-%d %H:%M:%S')
        return d > dd

movie/forms.py
from django import forms
from django.db.models import fields
from django.forms.widgets import TimeInput
from .models import Movie
from .models import Show


class DateTimeInput(forms.DateTimeInput):
    input_type = 'date'


class TimInput(forms.TimeInput):
    input_type = 'time'


class MovieForm(forms.ModelForm):
    moviename = forms.CharField(max_length=255, required=True)
    poster = forms.FileField(required=True)
    ticket_price = forms.FloatField(required=True)

    class Meta:
        model = Movie
        fields = '__all__'


class ShowForm(forms.ModelForm):
    date = forms.DateField(
        widget=DateTimeInput()
    )
    time = forms.TimeField(
        widget=TimeInput()
    )

    class Meta:
        model = Show
        fields = '__all__'

movie/views.py
from datetime import datetime

from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.shortcuts import Http404, redirect, render
from django.utils.http import is_safe_url
from django.views.generic import CreateView, FormView, ListView, View
from .forms import MovieForm, ShowForm
from .models import *
from itertools import chain


class HomePage(View):
    def get(self, request, *args, **kwargs):
        movie_list = Movie.objects.all().order_by('-added')
        # top_list = movie_list[:3]
        # movie_list = movie_list[3:]
        context = {'movie_list': movie_list}
        return render(request, 'home.html', context)


class SearchView(ListView):
    template_name = 'search.html'

    def get_context_data(self, *args, **kwargs):
        context = super(SearchView, self).get_context_data(*args, **kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        print(request.GET)
        query = request.GET.get('q')
        if query is not None:
            query = query.strip()
            return Movie.objects.search(query).order_by('-added')
        else:
            return Movie.objects.all()


class MovieListView(ListView):
    def get_queryset(self):
        return Movie.objects.all().order_by('-added')

    def get_context_data(self, *args, **kwargs):
        context = super(MovieListView, self).get_context_data(*args, **kwargs)
        movies = Movie.objects.all().order_by('-added')
        context = {'movie_list': movies}
        print(movies)
        print(context)
        return context


def movie_details(request, movie_id):
    try:
        movie_info = Movie.objects.get(pk=movie_id)
        
        day1 = Show.objects.filter(movie=movie_id,
                                   date=datetime.today())
        day2 = Show.objects.filter(movie=movie_id,
                                   date=datetime.today()+timedelta(days=1))
        day3 = Show.objects.filter(movie=movie_id,
                                   date=datetime.today()+timedelta(days=2))
        shows = list(chain(day1, day2, day3))
    except Movie.DoesNotExist:
        raise Http404("Page does not exist")
    return render(request, 'movie/movie_detail.html',
                  {'movie': movie_info, 'show_list': shows})


@login_required
def add_movie(request):
    template_name = 'movie/add_movie.html'
    print("qa")
    if request.method == 'POST':
        new_movie = MovieForm(request.POST, request.FILES)
        if new_movie.is_valid():
            new_movie.save()
            return redirect('admin')
    else:
        new_movie = MovieForm()
    return render(request, template_name, {'form': new_movie})


@login_required
def add_show(request):
    template_name = 'movie/add_show.html'

    if request.method == 'POST':
        show = ShowForm(request.POST)
        if show.is_valid():
            print(show)
            show.save()
            return redirect('admin')
    else:
        show = ShowForm()
    return render(request, template_name, {'form': show})

templates/movie/add_movie.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Movie Ticket Booking System | Add Movie
{% endblock %}
{% block content %}
<div class="container justify-content-center">
<div class="row justify-content-center">
    <h1>Add Movie</h1>
    <div class="col-6">
    <form method="POST" enctype="multipart/form-data">
        {{form | crispy}}
        {% csrf_token %}
        <br>
        <button type="submit" class="btn btn-primary">Add Movie</button>    

    </form>    
    </div>
</div>    
</div>
{% endblock %}

templates/movie/add_show.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Movie Ticket Booking System | Add Show
{% endblock %}
{% block content %}
<div class="container justify-content-center">
<div class="row justify-content-center">
    <h1>Add Show</h1>
    <div class="col-6">
       <form method="POST">
        {{form | crispy}}
        {% csrf_token %}
        <br>
        <button type="submit" class="btn btn-primary">Add Show</button>    
    </form> 
    </div>   
    </div>
</div>    
{% endblock %}

templates/movie/movie_detail.html
{% extends "base.html" %}

{% block title %}
Movie Ticket Booking System | Movie Details
{% endblock %}

{% block content %}



<div class="container">
        <div class="row justify-content-center">
            <div class=" col-6">
            <div class="card h-100 shadow">
              <img src="{{ movie.poster.url }}" class="card-img-top" alt="{{ movie.moviename | title }}">
              <div class="card-body">
		        <h3>{{ movie.moviename | title }}</h3><br>
            <h3>Now Showing</h3>
              <p>
              <div class="card-footer">
                {% if show_list %}
                {% for show in show_list %}
                <div class="media">
                  
                  <div class="media-body">
                    <h4 class="media-heading">{{ show.screen }}</h4>
                  <ul>
                    <!--  -->
                      <li>{% if user.is_authenticated %}<a href="{% url 'booking:reserve_seat' show.id %}">{{ show.date|date:"M d, Y" }}  {{ show.time|time:"h:i A" }}</a>{% else %}<p>{{ show.date|date:"M d, Y" }}  {{ show.time|time:"h:i A" }}</p>{% endif %}</li>
                    
                    </ul> 
                    </div>
                  </div>
                  {% endfor %}
                  {% else %}
                  <p class="lead">No Shows</p>
                  {% endif %}
              </div>
            </div>
          </div>
          </div>
    </div>  
  </div>

{% endblock %}

templates/movie/movie_list.html
{% extends "base.html" %}

{% block title %}
    Movie Ticket Booking System | Movies
{% endblock %}

{% block content %}
<div class="container"> 
        <div class="text-center">
            <h2>MOVIES</h2>
        </div>
        <div class="row justify-content-center">
        {% for movie in movie_list %}
            <div class=" col-4">
            <div class="card h-100 shadow">
              <img src="{{ movie.poster.url }}" class="card-img-top" alt="{{ movie.moviename | title }}">
              <div class="card-body">
		        <h3><a href="{% url 'movie:detail' movie.id %}">{{ movie.moviename | title }}</a></h3>
                <p>
              <div class="card-footer">
                <p>{% if user.is_authenticated %} <a class="btn btn-primary" href="{% url 'movie:detail' movie.id %}" role="button">Book Now</a>
                  {% else %}
                  <a class="btn btn-primary" href="{% url 'login' %}" role="button">Streaming Now</a>
                  {% endif %}</p>
              </div>
            </div>
          </div>
          </div>
        {% endfor %}
    </div>  
</div>
{% endblock %}