booking/urls.py
from django.urls import path
from .views import detailBookingView, reserve_seat, BookingListView, BookingDeleteView
app_name = 'booking'
urlpatterns = [
    path('select-seat/<int:show_id>/', reserve_seat, name='reserve_seat'),
    path('booking/', BookingListView.as_view(), name='list'),
    path('booking/<str:btid>/delete/',
         BookingDeleteView.as_view(), name='delete'),
    path('booking/<str:btid>/', detailBookingView, name='detail'),
]

movie/urls.py
from django.urls import path
from .views import *
app_name = 'movie'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('<int:movie_id>/', movie_details, name='detail'),
    path('search/', SearchView.as_view(), name='search'),
    path('movies/', MovieListView.as_view(), name='movie-list'),
    path('admin/add-movie', add_movie, name='add-movie'),
    path('admin/add-show', add_show, name='add-show'),

]

movie_booking/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('movie.urls')),
    path('', include('booking.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

booking/forms.py
from django import forms
from movie.models import Booking, Seat


class SeatForm(forms.ModelForm):
    class Meta:
        model = Seat
        fields = ('screen',)


class BookingForm(forms.ModelForm):

    class Meta:
        model = Booking
        fields = '__all__'

booking/views.py
from django.shortcuts import render, get_object_or_404
from movie.models import Movie, Show, Screen, Show, Seat, Booking
from .forms import SeatForm, BookingForm
from django.urls import reverse_lazy
import datetime
from django.views.generic import ListView, DetailView, DeleteView
from django.shortcuts import redirect
from django.http.response import Http404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from datetime import datetime, timedelta

# Create your views here.


@login_required
def reserve_seat(request, show_id):
    template_name = 'booking/reserve_seat.html'
    try:
        show_info = Show.objects.get(pk=show_id)
        # print("show", show_info.screen)
    except Show.DoesNotExist:
        raise Http404("Page does not exist")
    form = SeatForm()
    movie = show_info.movie
    # print(movie)
    screen = show_info.screen
    price = movie.ticket_price
    # print(price)
    booked = Booking.objects.filter(movie=movie, show=show_info)
    booked_seats = []
    for i in booked:
        booked_seats.append(i.seat.seat_no)
    not_booked = [int(i) for i in range(1, 11) if i not in booked_seats]
    print(not_booked)
    if request.method == 'POST':
        form = SeatForm(request.POST)
        sno = request.POST.get('seat_no')
        print(sno)
        if form.is_valid() and sno != None:
            new_seat = form.save(commit=False)
            new_seat.user = request.user
            new_seat.movie = movie
            new_seat.show = show_info
            new_seat.seat_no = sno
            # print(request.user.id)
            new_seat.save()
            form = Booking()
            form.seat = new_seat
            form.movie = movie
            form.show = show_info
            form.id = form.transaction_id
            form.paid_by = request.user
            form.paid_amount = price
            form.seat = new_seat
            form.save()
            return redirect('/booking/')
    else:
        return render(request, template_name,
                      {'show_info': show_info, 'form': form, 'not_booked': not_booked})


@method_decorator(login_required, name='dispatch')
class BookingListView(ListView):
    template_name = 'booking/booking_list.html'

    def get_queryset(self):
        return Booking.objects.filter(paid_by=self.request.user)

@login_required
def detailBookingView(request, btid):
    template_name = 'booking/booking_detail.html'
    obj = get_object_or_404(Booking, id=btid, paid_by=request.user)
    # print(obj)
    print(obj.show)
    d = datetime.strptime((datetime.now()+timedelta(days=1)
                           ).strftime("%Y-%m-%d %H:%M:%S"), '%Y-%m-%d %H:%M:%S')
    dd = datetime.strptime(str(obj.show.date)+" "+str(
        obj.show.time), '%Y-%m-%d %H:%M:%S')
    # print(type(d))
    # print(type(dd))
    can_be_canceled = True if d < dd else False
    # print(can_be_canceled)

    return render(request, template_name, {"object": obj, "cancel": can_be_canceled})


@method_decorator(login_required, name='dispatch')
class BookingDeleteView(DeleteView):
    template_name = 'booking/booking_confirm_delete.html'
    model = Booking
    success_url = reverse_lazy('booking:list')

    def get_object(self, *args, **kwargs):
        btid = self.kwargs.get('btid')
        obj = get_object_or_404(Booking, id=btid)
        return obj

# @method_decorator(login_required,name='dispatch')
# def cancel_booking(request,btid):
#     template_name = 'booking/booking_confirm_delete.html'
#     success_url = reverse_lazy('booking:list')
#     obj = get_object_or_404(Booking, id=btid)
#     obj.seat

templates/booking/booking_confirm_delete.html
{% extends "base.html" %}

{% block title %}
    Movie Ticket Booking System | Delete
{% endblock %}

{% block content %}
    
    <div class="container">
        <div class="row justify-content-ceneter">
            <div class="col-8">
                <form action=""  method="POST">{% csrf_token %}
                <div class="row">
                <div class="col-sm-offset-3 col-sm-6">
                <p class="" style="font-size:25px">Are you sure you want to delete"{{ object }}"?</p>
                </div>
                </div>
                <div class="row">
                <div class="col-sm-offset-5 col-sm-6">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" class="btn btn-danger" value="Confirm" />
                </div>
                </div>
                </form>
            </div>
        </div>
    </div>
    
{% endblock %}

templates/booking/booking_detail.html
{% extends "base.html" %}
{% load tz %}
{% block title %}
    Movie Ticket Booking System | Booking
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
                <h2>Booking Details</h2>
            <hr /><br />
            <font size=4>
            <div class="row">
            <div class="">
            <label>Booking ID :- </label>
            </div>
            <div class="col-sm-8">
            {{ object.transaction_id }}
            </div>
            </div>
            <br />
            <div class="row">
            <div class="">
            <label>Booking Time :- </label>
            </div>
            <div class="col-sm-8">
            {{ object.timestamp }}
            </div>
            </div>
            <br />
            <div class="row">
            <div class="col-sm-offset-2 col-sm-2">
            <label>Movie  :- </label>
            </div>
            <div class="col-sm-8">
            {{ object.movie }}
            </div>
            </div>
            <br />
            <div class="row">
            <div class="">
            <label>Show Time :- </label>
            </div>
            <div class="col-sm-8">
            {{ object.show.date }} {{ object.show.time }}
            </div>
            </div>
            <br />
            <div class="row">
            <div class="">
            <label>Seat No :- </label>
            </div>
            <div class="col-sm-8">
            {{ object.seat.seat_no }}
            </div>
            </div>
            <br />
            <div class="row">
            <div class="">
            <label>Paid Amount :- </label>
            </div>
            <div class="col-sm-8">
            {{ object.paid_amount }}
            </div>
            </div>
            {% if cancel %}
                <div class="row">
                <div class="col-sm-offset-2 col-sm-8">
                <center>
                <a href="{% url 'booking:delete' btid=object.id %}" class="btn btn-danger">Cancel Ticket</a>
                </center>
                </div>
                </div>
            {% endif %}
            </font>
        </div>
    </div>
</div>
    
{% endblock %}

templates/booking/booking_list.html
{% extends "base.html" %}

{% block title %}
    Movie Ticket Booking System | Booking
{% endblock %}

{% block content %}
    
    <div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <h2>My Bookings</h2>
    <hr />
    <br /><br />
    {% if object_list %}
    
    <div class="col-sm-offset-1 col-sm-10" style="background-color:#e7e7e7">
        <ul>
            <font size="4">
                
                {% for book in object_list %}
                <li> {{ book.movie }}  <a href="{{ book.get_absolute_url }}">{{ book }}</a></li>
                <br />
    {% endfor %}
</font>
</ul>
</div>

{% else %}
<p class="text-center lead">No Bookings to Show</p>
    {% endif %}
</div>
</div>
</div>
{% endblock %}

templates/booking/reserve_seat.html
{% extends "base.html" %}

{% block title %}
Movie Ticket Booking System | Reserve Seats
{% endblock %}

{% block content %}
<div class="container justify-content-center">
	{% if not_booked %}
	<h1>Select Seats</h1>
	<h2>{{ show_info }}</h2>
	<div class="seatDiv">
		<div class="form-group">
			<form method="post" action="" class="form-group">
				{% csrf_token %}
				{{ form.as_p }}
				<label for="seat_no">Seat No</label>
				<select name="seat_no" id="cars">
				{% for i in not_booked %}
				<option value="{{ i }}">{{ i }}</option>
				{% endfor %}
				</select>
				<input type="hidden" name="show_id" id="show_id" value="{{ show_info.id }}" readonly />
				<br /><br />
				<button type="submit" class="btn btn-warning">Confirm</button>
			</form>
		</div>
	</div>
	{% else %}
	<h1>No seats are available</h1>
	{% endif %}
</div>

{% endblock %}