movie/urls.py
from django.urls import path
from .views import *
app_name = 'movie'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('<int:movie_id>/', movie_details, name='detail'),
    path('search/', SearchView.as_view(), name='search'),
    path('movies/', MovieListView.as_view(), name='movie-list'),
    path('admin/add-movie', add_movie, name='add-movie'),
    path('admin/add-show', add_show, name='add-show'),

]

movie_booking/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('movie.urls')),
    path('', include('booking.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie/models.py
import datetime
from django.urls import reverse
from django.contrib.auth import get_user_model
import uuid
from django.db import models
from django.db.models import Q
from django.urls.base import reverse
from datetime import datetime, timedelta
# Create your models here.


class MovieQuerySet(models.query.QuerySet):
    def search(self, query):
        lookup = (
            Q(moviename__icontains=query)
        )
        return self.filter(lookup).distinct()


class MovieManager(models.Manager):
    def get_queryset(self):
        return MovieQuerySet(self.model, self._db)

    def search(self, query):
        return self.get_queryset().search(query)


User = get_user_model()
# Create your models here.


class Screen(models.Model):
    name = models.CharField(max_length=20)
    seats = models.IntegerField(default=10)

    def __str__(self) -> str:
        return str("Screen : "+self.name)


class Movie(models.Model):
    moviename = models.CharField("Movie Name", max_length=20, blank=False)
    poster = models.ImageField(
        null=True, blank=False, upload_to='%Y/%m/%d/')
    ticket_price = models.FloatField(null=False, blank=False)
    added = models.DateTimeField(auto_now_add=True)
    screen = models.ManyToManyField(Screen)
    objects = MovieManager()

    def get_absolute_url(self):
        return reverse('movie:detail', kwargs={'movie_id': self.pk})

    def __str__(self):
        return self.moviename

class Show(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    screen = models.ForeignKey(Screen, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()

    def __str__(self):
        return str(self.movie)+" : "+str(self.screen)+"-"+str(self.date)+"-"+str(self.time)


class Seat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    show = models.ForeignKey(Show, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    screen = models.ForeignKey(Screen, on_delete=models.CASCADE)
    seat_no = models.IntegerField()

    def __str__(self):
        return str(self.id)


class Booking(models.Model):
    id = models.CharField(max_length=255, primary_key=True)
    transaction_id = models.UUIDField(unique=True, editable=False,
                                      default=uuid.uuid4)
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)
    seat = models.ForeignKey(Seat, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    show = models.ForeignKey(Show, on_delete=models.CASCADE)
    paid_amount = models.DecimalField(max_digits=8, decimal_places=2)
    paid_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return str("Booking ID # "+str(self.transaction_id))

    def get_absolute_url(self):
        return reverse('booking:detail', kwargs={'btid': self.id})

    @property
    def cancel_time(self):
        d = datetime.now()+timedelta(days=1)
        dd = datetime.strptime(str(self.show.date)+" "+str(
            self.show.time), '%Y-%m-%d %H:%M:%S')
        return d > dd

templates/admin.html
{% extends "base.html" %}
{% block title %}
    Movie Ticket Booking System | Admin Panel
{% endblock %}
{% block content %}
<div class="container justtify-content-center">
    <h1>Welome to admin Menu</h1>
    <a href="/admin/add-movie" class="btn btn-primary">Add new Movie</a>
    <a href="/admin/add-show" class="btn btn-primary">Add Show</a>
</div>
{% endblock %}

templates/base.html
{% load static %}
{% load crispy_forms_tags %}
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
<script src="{% static '/js/bootstrap.bundle.js' %}"></script>

<!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

<title>{% block title %}Home | Movie Booking System{% endblock %}</title>
<style>
</style>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded" aria-label="Eleventh navbar example">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Movie Booking System</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample09">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movie:movie-list' %}">Movies</a>
            </li>
            {% if user.is_authenticated %}
            <li><a class = "nav-link"href="/booking/">My Booking</a></li>
            {% if user.is_admin %}
            <li><a class = "nav-link"href="/admin/">Admin Menu</a></li>
            {% endif %}
            {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
              <li class="active"><p><strong>Welcome {{ user.firstname|title }} {{user.lastname|title}}</strong></p></li>&nbsp;
              <li class=" active"><a class = "nav-link" href="/logout/">Sign Out</a></li>
              {% else %}
              <li class="active"><a class = "nav-link" href="{% url 'login' %}" id="signIn">Sign In</a></li>
              <li><a class = "nav-link" href="{% url 'register' %}">Register</a></li>
              {% endif %}
            </ul>
        </div>
      </div>
    </nav>

    <div style="margin-right:5px;">
      <form class="navbar-form navbar-right search-form" role="search" action="{% url 'movie:search' %}">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search">
            <span class="input-group-btn input-group-sm">
              &nbsp;<button type="submit" class="btn btn-primary">Search</button>
            </span>
            </div>  
            </form>
          </div>
        </div>
      </div>
    </nav>
    <script type="text/javascript">
 
  
  $(document).ready(function(){

    var searchForm = $('.search-form');
    console.log(searchForm)
    var searchInput = searchForm.find("[name='q']");
    console.log(searchInput)
    var typingTimer;
    var typingInterval = 500;
    console.log("hello")
    searchInput.keyup(function(event){
        clearTimeout(typingTimer);
        console.log(searchInput.val())
        typingTimer = setTimeout(function(){
          console.log("Hello w")
        var query = searchInput.val();
        window.location.href='/search/?q='+query;
    },typingInterval,searchInput);
    });
    searchInput.keydown(function(event){
        clearTimeout(typingTimer);
       
    });
  });
</script>
<div id="content" class="container-fluid">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %}
    Movie Ticket Booking System | |Home
{% endblock %}
{% block content %}
<div class="container-fluid bg-light " style="margin-top: 30px;">
    <style type="text/css" media="screen">
    img {height:auto;max-width:100%; width: auto;border:none;display:block;}
    </style>
    <br><br><br>
    <div class="container">
      <div class="row justify-content-center">
        {% for movie in movie_list %}
          <div class=" col-4">
            <div class="card h-100 shadow">
              <img src="{{ movie.poster.url }}" class="card-img-top" alt="image">
              <div class="card-body">
		        <h1>{{ movie.moviename | title  }}</h1>
                <p>
              <div class="card-footer">
                {% if user.is_authenticated %}
                <a class="btn btn-lg btn-primary" href="{{ movie.get_absolute_url }}" role="button">Book Now</a>
                {% else %}
                <a class="btn btn-lg btn-primary" href="/login" role="button">Streaming Now</a>
                {% endif %}
              </div>
            </div>
          </div>
          </div>
        {% endfor %}
      </div>
    </div>
</div>
{% endblock %}

templates/search.html
{% extends "base.html" %}

{% block title %}
    Movie Booking System
{% endblock %}

{% block content %}
<div class="container">
<div class="row justify-content-center text-center">
<h1>Results for <b>"{{ query }}"</b></h1> 
<hr/>
</div>
</div>
<div class="container">
        {% if movie_list %}
        <div class="row justify-content-center">
        {% for movie in movie_list %}
            <div class=" col-4">
            <div class="card h-100 shadow">
              <img src="{{ movie.poster.url }}" class="card-img-top" alt="{{ movie.moviename | title }}">
              <div class="card-body">
		        <h3><a href="{% url 'movie:detail' movie.id %}">{{ movie.moviename | title }}</a></h3>
                <p>
              <div class="card-footer">
                <p>{% if user.is_authenticated %} <a class="btn btn-primary" href="{% url 'movie:detail' movie.id %}" role="button">Book Now</a>
                    {% else %}
                    <a class="btn btn-primary" href="{% url 'login' %}" role="button">Watch Now</a>
                    {% endif %}</p>
              </div>
            </div>
          </div>
          </div>
        {% endfor %}
    </div>  
    {% else %}
    <p class="lead text-center">No Items Found!!!</p>
    {% endif %}
</div>
{% endblock %}